import assert from "node:assert/strict";
import test from "node:test";
import React from "react";
import { JSDOM } from "jsdom";
import { IDBFactory } from "fake-indexeddb";

// DOM integration test, entirely offline. No microphone, browser credentials or paid API.
test("the workspace keeps files, chats, memories and editable website versions across reloads", { timeout: 30000 }, async () => {
  const dom = new JSDOM("<!doctype html><html><body></body></html>", { url: "https://ki-chat.test" });
  const indexedDB = new IDBFactory();
  for (const [key, value] of Object.entries({ window: dom.window, document: dom.window.document, navigator: dom.window.navigator, HTMLElement: dom.window.HTMLElement, Element: dom.window.Element, Node: dom.window.Node, MutationObserver: dom.window.MutationObserver, localStorage: dom.window.localStorage, getComputedStyle: dom.window.getComputedStyle, indexedDB, IS_REACT_ACT_ENVIRONMENT: true })) Object.defineProperty(globalThis, key, { configurable: true, writable: true, value });
  dom.window.indexedDB = indexedDB;
  dom.window.matchMedia = (query) => ({ matches: query.includes("pointer: fine"), media: query, addEventListener() {}, removeEventListener() {} });
  dom.window.HTMLElement.prototype.scrollIntoView = () => {};
  const downloads = []; const blobs = new Map();
  URL.createObjectURL = (blob) => { const url = `blob:test-${blobs.size}`; blobs.set(url, blob); return url; };
  URL.revokeObjectURL = () => {};
  dom.window.HTMLAnchorElement.prototype.click = function () { downloads.push({ name: this.download, url: this.href }); };
  const calls = []; const imageCalls = [];
  const png = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=";
  globalThis.fetch = async (url, options) => {
    if (url === "/api/config") return Response.json({ geminiConfigured: true, model: "gemini-3.6-flash" });
    if (url === "/api/images") { imageCalls.push(JSON.parse(options.body)); return new Response(Buffer.from(png, "base64"), { headers: { "Content-Type": "image/png" } }); }
    if (url !== "/api/chat") throw new Error("Unexpected request in offline test");
    const body = JSON.parse(options.body); calls.push(body);
    if (body.mode === "website") return Response.json({ answer: "<!doctype html><html><body><h1>Mein Café</h1><button onclick='this.textContent=42'>Rechnen</button></body></html>" });
    const answer = "## Fertig\n\nDeine Datei ist ausgewertet.\n\n| Monat | Umsatz |\n| --- | --- |\n| Januar | 12 |\n\n```javascript\nconst sum = 12;\n```";
    const data = [{ type: "delta", text: "## Fertig\n" }, { type: "done", answer, sources: body.webSearch ? [{ title: "Testquelle", url: "https://example.org/quelle" }] : undefined }];
    return new Response(data.map((event) => `data: ${JSON.stringify(event)}\n\n`).join(""), { headers: { "Content-Type": "text/event-stream" } });
  };
  dom.window.localStorage.setItem("ki-chat-messages", JSON.stringify([{ id: "old", role: "user", content: "Mein alter Chat bleibt erhalten" }]));
  const { render, screen, within, waitFor, fireEvent, cleanup } = await import("@testing-library/react");
  const userEvent = (await import("@testing-library/user-event")).default;
  const Home = (await import("../app/page.tsx")).default;
  const { loadWorkspace } = await import("../lib/workspace-storage.ts");
  const user = userEvent.setup({ document: dom.window.document });
  try {
    render(React.createElement(Home));
    await screen.findByText("Mein alter Chat bleibt erhalten");
    await user.click(screen.getByRole("button", { name: "Neuer Chat", exact: true }));
    await user.type(screen.getByRole("textbox", { name: "Deine Nachricht" }), "Bitte analysiere meinen Umsatz");
    const csv = new dom.window.File(["Monat,Umsatz\nJanuar,12"], "umsatz.csv", { type: "text/csv" });
    Object.defineProperty(csv, "arrayBuffer", { value: async () => new TextEncoder().encode("Monat,Umsatz\nJanuar,12").buffer });
    await user.upload(document.querySelector("input[type=file][multiple]"), csv);
    await screen.findByRole("button", { name: "umsatz.csv entfernen" });
    await user.click(screen.getByRole("button", { name: "Websuche", exact: true }));
    assert.equal(screen.getByRole("button", { name: "Nachricht senden" }).disabled, true);
    await user.click(screen.getByRole("checkbox", { name: /Websuche aktivieren/ }));
    await user.click(screen.getByRole("button", { name: "Analyse", exact: true }));
    await user.click(screen.getByRole("button", { name: "Nachricht senden" }));
    await screen.findByRole("heading", { name: "Fertig" });
    assert.equal(calls.length, 1); assert.equal(calls[0].analysis, true); assert.equal(calls[0].webSearch, true);
    assert.equal(calls[0].messages[0].attachments[0].name, "umsatz.csv");
    assert.equal(screen.getByRole("link", { name: /Testquelle/ }).href, "https://example.org/quelle");
    assert.equal(screen.getByRole("table").textContent.includes("Januar"), true);
    await user.clear(screen.getByRole("textbox", { name: "Chat umbenennen" }));
    await user.type(screen.getByRole("textbox", { name: "Chat umbenennen" }), "Umsatzanalyse");
    const question = screen.getByText("Bitte analysiere meinen Umsatz", { exact: true }).closest("article");
    await user.click(within(question).getByRole("button", { name: "Merken", exact: true }));
    const memoryInput = screen.getByRole("textbox", { name: "Neue Erinnerung" });
    await user.clear(memoryInput); await user.type(memoryInput, "Meine Markenfarbe ist Blau");
    await user.click(screen.getByRole("button", { name: "Merken", exact: true }));
    await user.type(screen.getByLabelText("Wie darf ich dich nennen?"), "Alex");
    await user.selectOptions(screen.getByLabelText("Darstellung"), "dark");
    await waitFor(() => assert.equal(document.documentElement.dataset.theme, "dark"));
    await waitFor(async () => { const stored = await loadWorkspace(); assert.equal(stored.settings.name, "Alex"); assert.equal(stored.chats.some((c) => c.title === "Umsatzanalyse"), true); assert.equal(stored.memories[0], "Meine Markenfarbe ist Blau"); }, { timeout: 4000 });
    await user.click(screen.getByRole("button", { name: "Sicherung herunterladen" }));
    const backup = JSON.parse(await blobs.get(downloads.at(-1).url).text());
    assert.equal(backup.chats.length, 2); assert.equal(JSON.stringify(backup).includes("apiKey"), false);
    await user.click(screen.getByRole("button", { name: "Neuer Chat", exact: true }));
    await user.type(screen.getByRole("textbox", { name: "Deine Nachricht" }), "Eine neue Frage");
    await user.click(screen.getByRole("button", { name: "Nachricht senden" }));
    await screen.findByRole("heading", { name: "Fertig" });
    assert.match(calls.at(-1).memory, /Markenfarbe ist Blau/); assert.match(calls.at(-1).instructions, /Alex/);
    await user.click(screen.getByRole("button", { name: "Neues Webseitenprojekt" }));
    await user.type(screen.getByRole("textbox", { name: "Webseite oder Änderung beschreiben" }), "Erstelle eine Café-Webseite");
    await user.click(screen.getByRole("button", { name: "Webseite erstellen", exact: true }));
    await screen.findByTitle("Vorschau deiner Webseite");
    assert.equal(screen.getByTitle("Vorschau deiner Webseite").getAttribute("sandbox"), "allow-scripts");
    await user.click(screen.getByRole("button", { name: "Code bearbeiten" }));
    fireEvent.change(screen.getByRole("textbox", { name: "HTML-Code bearbeiten" }), { target: { value: "<!doctype html><html><body>Meine eigene Änderung</body></html>" } });
    await waitFor(async () => { const stored = await loadWorkspace(); assert.match(stored.projects[0].html, /Meine eigene Änderung/); assert.match(stored.projects[0].versions[0].html, /Mein Café/); }, { timeout: 4000 });
    await user.click(screen.getByRole("button", { name: "Bilder erstellen", exact: true }));
    const original = new dom.window.File([Buffer.from(png, "base64")], "original.png", { type: "image/png" });
    Object.defineProperty(original, "arrayBuffer", { value: async () => Uint8Array.from(Buffer.from(png, "base64")).buffer });
    await user.upload(screen.getByLabelText("Bild zum Bearbeiten hochladen"), original);
    await screen.findByAltText("Dein Originalbild");
    await user.type(screen.getByLabelText("Was soll sich am Bild ändern?"), "Mache den Hintergrund blau");
    assert.equal(screen.getByRole("button", { name: "Bild bearbeiten", exact: true }).disabled, true);
    await user.click(screen.getByRole("checkbox", { name: "Ich möchte kostenpflichtige Bilder erstellen." }));
    await user.click(screen.getByRole("button", { name: "Bild bearbeiten", exact: true }));
    await screen.findByText("Dein Bild ist fertig und auf diesem Gerät gespeichert.");
    assert.equal(imageCalls.length, 1); assert.equal(imageCalls[0].reference.data, png);
    assert.equal(imageCalls[0].reference.name, "original.png"); assert.equal(imageCalls[0].billingAcknowledged, true);
    cleanup();
    render(React.createElement(Home));
    await screen.findByRole("button", { name: "Umsatzanalyse", exact: true });
    await user.click(screen.getByRole("button", { name: "Umsatzanalyse", exact: true }));
    await screen.findByRole("heading", { name: "Fertig" });
    assert.equal(screen.getByRole("link", { name: "umsatz.csv", exact: true }).getAttribute("download"), "umsatz.csv");
    await user.click(screen.getByRole("button", { name: /Einstellungen & Gedächtnis/ }));
    assert.equal(screen.getByLabelText("Wie darf ich dich nennen?").value, "Alex");
    assert.equal(screen.getByText("Meine Markenfarbe ist Blau", { exact: true }).textContent, "Meine Markenfarbe ist Blau");
    await user.click(screen.getByRole("button", { name: "Bilder erstellen", exact: true }));
    await screen.findByRole("button", { name: "Bild öffnen: Mache den Hintergrund blau" });
    assert.equal(screen.getByRole("checkbox", { name: "Ich möchte kostenpflichtige Bilder erstellen." }).checked, false);
  } finally { cleanup(); dom.window.close(); }
});
