"use client";
import { FormEvent, useRef, useState } from "react";
import { Brain, Check, Download, Globe, ImagePlus, Mic, Plus, Settings2, Terminal, Upload, X } from "lucide-react";
import { downloadText } from "../lib/files";
import { parseWorkspace, type Settings, type Workspace } from "../lib/workspace";

export default function SettingsPanel({ workspace, onSettings, onMemories, onImport, configured, memoryDraft = "", onDraftConsumed }: { workspace: Workspace; onSettings: (settings: Settings) => void; onMemories: (memories: string[]) => void; onImport: (workspace: Workspace) => void; configured: boolean; memoryDraft?: string; onDraftConsumed: () => void }) {
  const [draft, setDraft] = useState(memoryDraft.slice(0, 500)); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  const s = workspace.settings;
  function change(values: Partial<Settings>) { onSettings({ ...s, ...values }); }
  function add(event: FormEvent) { event.preventDefault(); const text = draft.trim(); if (!text) return; if (workspace.memories.length >= 100) { setError("Du kannst bis zu 100 Erinnerungen speichern."); return; } onMemories([...new Set([text, ...workspace.memories])]); setDraft(""); onDraftConsumed(); setNotice("Erinnerung hinzugefügt."); }
  async function importBackup(file?: File) { if (!file) return; setError(""); try { if (file.size > 64 * 1024 * 1024) throw new Error("Die Sicherung darf höchstens 64 MB groß sein."); const imported = parseWorkspace(JSON.parse(await file.text())); onImport(imported); setNotice(`${imported.chats.length} Chats und ${imported.projects.length} Projekte als zusätzliche Kopien importiert. Deine aktuellen Einstellungen bleiben erhalten.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Die Sicherung konnte nicht gelesen werden."); } finally { if (inputRef.current) inputRef.current.value = ""; } }
  return <section className="settings-workspace"><div className="panel-intro"><span className="welcome-kicker">SO, WIE DU ARBEITEST</span><h2>Dein Assistent. Deine Regeln.</h2><p>Persönliche Antworten, ein Gedächtnis unter deiner Kontrolle und eine Sicherung für deine Arbeit.</p></div>
    <div className="settings-grid"><section className="settings-card"><h3><Settings2 size={19}/>Persönlichkeit & Darstellung</h3><label>Wie darf ich dich nennen?<input value={s.name} onChange={(e) => change({ name: e.target.value })} placeholder="Dein Name" maxLength={80}/></label><label>Wie soll ich antworten?<select value={s.tone} onChange={(e) => change({ tone: e.target.value as Settings["tone"] })}><option value="normal">Ausgewogen</option><option value="short">Kurz und direkt</option><option value="detailed">Ausführlich mit Beispielen</option></select></label><label>Deine persönlichen Anweisungen<textarea value={s.instructions} onChange={(e) => change({ instructions: e.target.value })} maxLength={3000} placeholder="Zum Beispiel: Erkläre Fachbegriffe. Verwende Schweizer Rechtschreibung. Gib mir konkrete nächste Schritte." rows={5}/></label><label>Darstellung<select value={s.theme} onChange={(e) => change({ theme: e.target.value as Settings["theme"] })}><option value="light">Hell</option><option value="dark">Dunkel</option><option value="system">Wie mein Gerät</option></select></label></section>
    <section className="settings-card"><h3><Brain size={19}/>Gedächtnis</h3><p>Deine gespeicherten Hinweise werden bei künftigen Fragen und Projekten berücksichtigt. Du entscheidest, was bleibt. Das zugrunde liegende Modell wird dadurch nicht neu trainiert.</p><label className="settings-check"><input type="checkbox" checked={s.memoryEnabled} onChange={(e) => change({ memoryEnabled: e.target.checked })}/>Gespeicherte Erinnerungen verwenden</label><form className="memory-add" onSubmit={add}><textarea value={draft} onChange={(e) => setDraft(e.target.value)} maxLength={500} placeholder="Meine Marke heißt … und meine Lieblingsfarbe ist …" aria-label="Neue Erinnerung" rows={3}/><button disabled={!draft.trim()}><Plus size={16}/>Merken</button></form><div className="settings-memories">{workspace.memories.map((memory, i) => <div key={`${memory}-${i}`}><span>{memory}</span><button onClick={() => onMemories(workspace.memories.filter((_, index) => index !== i))} aria-label={`Erinnerung entfernen: ${memory.slice(0, 60)}`}><X size={15}/></button></div>)}</div>{!workspace.memories.length && <p className="settings-muted">Noch keine Erinnerungen. Du kannst auch direkt an einer Chatnachricht auf „Merken“ klicken.</p>}</section>
    <section className="settings-card"><h3><Download size={19}/>Sichern & Wiederherstellen</h3><p>Chats mit Anhängen, Webseiten mit Versionen und Erinnerungen werden in diesem Browser gespeichert. Es gibt noch keine Synchronisierung zwischen Geräten.</p><div className="backup-actions"><button onClick={() => { downloadText(`ki-chat-sicherung-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify(workspace, null, 2), "application/json"); setNotice("Die Sicherung wurde zum Download bereitgestellt."); }}><Download size={16}/>Sicherung herunterladen</button><button onClick={() => inputRef.current?.click()}><Upload size={16}/>Sicherung importieren</button><input ref={inputRef} type="file" accept=".json,application/json" hidden onChange={(e) => void importBackup(e.target.files?.[0])}/></div><p className="settings-muted">Die Sicherung enthält deine persönlichen Inhalte, aber keinen API-Schlüssel. Bilder aus dem Bilderstudio bitte dort separat herunterladen. Gelöschte Browserdaten können ohne Sicherung nicht wiederhergestellt werden.</p></section>
    <section className="settings-card capability-card"><h3><Check size={19}/>Deine Funktionen</h3><ul><li><Check size={15}/>Gespeicherte Chats, Suche und Export</li><li><Check size={15}/>Markdown, Tabellen und Code zum Herunterladen</li><li><Globe size={15}/>Websuche mit Quellen · {configured ? "über Gemini, optionale Zusatzkosten" : "Gemini-Einrichtung erforderlich"}</li><li><Terminal size={15}/>PDFs, Bilder, CSV und Python-Analyse · {configured ? "über Gemini" : "Gemini-Einrichtung erforderlich"}</li><li><Mic size={15}/>Diktieren und Vorlesen · abhängig vom Browser</li><li><ImagePlus size={15}/>Bilderstudio · Google-Abrechnung erforderlich</li><li><Check size={15}/>Webseiten mit Codeeditor und Versionen</li></ul><div className="capability-limit"><strong>Noch nicht eingerichtet</strong><p>Geräteübergreifende Speicherung, Verbindungen zu E-Mail und Kalender sowie selbstständig laufende Hintergrundaufgaben benötigen zusätzliche Dienste und eigene Berechtigungen.</p></div></section></div>
    {error && <p className="panel-error" role="alert">{error}</p>}{notice && <p className="panel-notice" role="status">{notice}</p>}
  </section>;
}
